spring:
  application:
    name: employee-ms
    datasource:
      driver-class:
        name: org.postgresql.Driver
      username: postgres
      password: root
      host: localhost
      port : 5433
      database: employee
      url: jdbc:postgresql://${username}:${password}@${host}:${port}/${database}
server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

